# make_game_titles_cn.ps1
#从 gamename.csv(HDL-Batch-installer 的 PS2 游戏 ID 数据库,含日/美/欧各区)生成
# src/game_titles_cn.h —— 记忆卡存档目录名(产品代码)→ 简体中文标题对照表。
#输出表按 code 的 ASCII 序排序(供 filer_browser.c 中 lookupCNTitle 二分查找),UTF-8 无 BOM。
#翻译流程(每行):精确短语表(定制完整标题) → 系列表(系列中文名+副标题/序号自动拼接) → 未命中跳过(回退显示原标题)。
$ErrorActionPreference = 'Stop'
$csvPath = Join-Path $PSScriptRoot 'gamename.csv'
$outPath = Join-Path $PSScriptRoot 'src\game_titles_cn.h'

#========== 第1层:精确短语(命中即输出完整中文标题;修复序号歧义与独立游戏) ==========
$exact = @(
	@('Shadow of the Colossus','旺达与巨像'), @('Wander to Kyozou','旺达与巨像'),
	@('Okami','大神'), @('Ookami','大神'),
	@('Ico','ICO'),
	@('Katamari Damacy','块魂'), @('Minna Daisuki Katamari','我们爱块魂'),
	@('Genji','源氏'),
	@('God Hand','上帝之手'),
	@('Odin Sphere','奥丁领域'),
	@('Kuon','九怨'),
	@('Rule of Rose','蔷薇法则'),
	@('The Suffering','苦难'),
	@('Manhunt','侠盗猎魔'),
	@('Bully','恶霸鲁尼'),
	@('Gungrave','铳墓'),
	@('GUNgrave','铳墓'),
	@('Red Dead Revolver','荒野大镖客'),
	@('Siren','死魂曲'), @('Forbidden Siren','死魂曲'),
	@('The Bouncer','神佑擂手'),
	@('Shinobi','忍·Shinobi'),
	@('Otogi','御伽'),
	@('Way of the Samurai','武士道'),
	@('Max Payne','马克思·佩恩'),
	@('Enter the Matrix','黑客帝国：进入矩阵'), @('The Matrix','黑客帝国'),
	@('Lord of the Rings','指环王'), @('The Two Towers','指环王：双塔奇兵'), @('Return of the King','指环王：王者归来'),
	@('Harry Potter','哈利·波特'),
	@('Star Wars','星球大战'),
	@('Spider-Man','蜘蛛侠'), @('Spider Man','蜘蛛侠'),
	@('Batman','蝙蝠侠'),
	@('X-Men','X战警'),
	@('The Punisher','惩罚者'), @('Punisher','惩罚者'),
	@('GoldenEye','黄金眼'),
	@('James Bond','007系列'),
	@('Nightfire','007：夜火'),
	@('Agent Under Fire','007：特工在行动'),
	@('Everything or Nothing','007：万事皆无'),
	@('Half-Life','半条命'),
	@('Quake','雷神之锤'),
	@('Unreal','虚幻竞技场'),
	@('Serious Sam','英雄萨姆'),
	@('Red Faction','红色派系'),
	@('Freedom Fighters','自由战士'),
	@('Killzone','杀戮地带'),
	@('Deus Ex','杀出重围'),
	@('Commandos','盟军敢死队'),
	@('Hitman','终极刺客'),
	@('Splinter Cell','分裂细胞'),
	@('Prince of Persia','波斯王子'),
	@('Tomb Raider','古墓丽影'),
	@('Myst','神秘岛'),
	@('Rayman','雷曼'),
	@('Ghost Recon','幽灵行动'),
	@('Rainbow Six','彩虹六号'),
	@('True Crime','真实犯罪'),
	@('Shrek','怪物史莱克'),
	@('Crazy Taxi','疯狂出租车'),
	@('House of the Dead','死亡之屋'),
	@('Vampire Night','吸血鬼之夜'),
	@('Time Crisis','时间危机'), @('Crisis Zone','时间危机：危机地带'),
	@('Point Blank','点空白'),
	@('Mr. Driller','钻地先生'),
	@('Klonoa','风之克罗诺亚'),
	@('Viewtiful Joe','红侠乔伊'),
	@('Killer 7','杀手7'),
	@('Chaos Legion','混沌军团'),
	@('Clock Tower','时钟塔'),
	@('Haunting Ground','狂气古城'), @('Demento','狂气古城'),
	@('The Getaway','伦敦黑帮'),
	@('Twisted Metal','烈火战车'),
	@('Destruction Derby','毁灭德比'),
	@('Stuntman','特技车手'),
	@('Drakengard','龙背上的骑兵'),
	@('Musashi','武藏传'),
	@('Romancing SaGa','浪漫沙加'), @('Unlimited Saga','无限沙加'),
	@('SaGa Frontier','沙加前线'),
	@("King's Field",'国王密令'),
	@('EverQuest','无尽的任务'),
	@("Baldur's Gate",'博德之门：黑暗联盟'),
	@('The Sims','模拟人生'),
	@('Harvest Moon','牧场物语'),
	@('Monster Rancher','怪物农场'),
	@('Digimon','数码宝贝'),
	@('Chocobo','陆行鸟'),
	@('Itadaki Street','富豪街'),
	@('Doko Demo Issho','随身玩伴·多罗猫'), @('Dokodemo Issyo','随身玩伴·多罗猫'),
	@('Boku no Natsuyasumi','我的暑假'),
	@('Natsuyasumi','我的暑假'),
	@('Taiko no Tatsujin','太鼓达人'),
	@('Densha de Go','电车GO'),
	@('Guitar Hero','吉他英雄'),
	@('Dance Dance Revolution','DDR跳舞机'), @('DDR','DDR跳舞机'),
	@('Karaoke Revolution','卡拉OK革命'),
	@('GuitarFreaks','吉他高手'), @('DrumMania','鼓手高手'),
	@('beatmania','beatmania打拍机'), @('IIDX','beatmania IIDX'),
	@('EyeToy','EyeToy体感游戏'),
	@('SingStar','SingStar歌星'),
	@('Buzz!','Buzz智力问答'),
	@('I.Q Remix','智能方块'), @('Intelligent Qube','智能方块'),
	@('Bomberman','炸弹人'),
	@('Puyo Puyo','魔法气泡'),
	@('Ikaruga','斑鸠'),
	@('Gradius','宇宙巡航机'),
	@('R-Type','R-Type纵向射击'),
	@('Shikigami no Shiro','式神之城'), @('Castle Shikigami','式神之城'),
	@('Contra','魂斗罗'),
	@('Metal Slug','合金弹头'),
	@('Fatal Fury','饿狼传说'), @('Garou','饿狼传说：狼之印记'),
	@('Art of Fighting','龙虎之拳'),
	@('The Last Blade','月华剑士'),
	@('Kinnikuman','金肉人'),
	@('Def Jam','Def Jam嘻哈格斗'),
	@('Rumble Roses','摔角玫瑰'),
	@('All Star Pro-Wrestling','全明星职业摔角'),
	@('WWE','WWE美式摔角'), @('SmackDown','WWE SmackDown'),
	@('UFC','UFC终极格斗'),
	@('K-1','K-1格斗'), @('K1','K-1格斗'),
	@('Zettai Zetsumei Toshi','绝体绝命都市'), @('Disaster Report','绝体绝命都市'),
	@('Yoake mae yori ruriiro na','夜明前的琉璃色'),
	@('Hiiro no Kakera','绯色碎片'),
	@('Harukanaru Toki no Naka de','遥远时空中'),
	@('Angelique','安杰莉可'),
	@('Clannad','CLANNAD'),
	@('Little Busters','Little Busters'),
	@('Higurashi','寒蝉鸣泣之时'),
	@('Suzumiya Haruhi','凉宫春日'),
	@('Lucky Star','幸运星'),
	@('To Heart','To Heart'), @('ToHeart','To Heart'),
	@('Tokimeki','心跳回忆'),
	@('Detective Conan','名侦探柯南'), @('Meitantei Conan','名侦探柯南'),
	@('Evangelion','新世纪福音战士'),
	@('Code Geass','叛逆的鲁鲁修'),
	@('Eureka Seven','交响诗篇'),
	@('Fullmetal Alchemist','钢之炼金术师'), @('Full Metal Alchemist','钢之炼金术师'), @('Hagane no Renkinjutsushi','钢之炼金术师'),
	@('Naruto','火影忍者'),
	@('Bleach','死神'),
	@('One Piece','海贼王'),
	@('Dragon Ball','龙珠'), @('Dragonball','龙珠'),
	@('Inuyasha','犬夜叉'), @('InuYasha','犬夜叉'),
	@('Rurouni Kenshin','浪客剑心'),
	@('Yu Yu Hakusho','幽游白书'),
	@('Yu-Gi-Oh','游戏王'),
	@('Zatch Bell','金色卡修'), @('Gashbell','金色卡修'), @('Konjiki no Gash','金色卡修'),
	@('D.Gray-man','驱魔少年'),
	@('Saru! Get You','捉猴啦'), @('Saru Battle','捉猴啦'), @('Piposaru','捉猴啦'), @('Ape Escape','捉猴啦'),
	@('Macross','超时空要塞'),
	@('Sakura Taisen','樱花大战'), @('Sakura War','樱花大战'),
	@('Zoids','索斯机械兽'),
	@('Mission: Impossible','碟中谍'), @('Mission Impossible','碟中谍'),
	@('Terminator','终结者'),
	@('Transformers','变形金刚'),
	@('Sega Ages','世嘉时代合集'),
	@('Alpine Racer','高山滑雪'),
	@('Sno-Cross','雪地摩托'), @('Sled Storm','雪地风暴'),
	@('Splashdown','水上摩托'),
	@('ATV Offroad','ATV全地形车'),
	@('Hot Shots Golf','大众高尔夫'),
	@('Initial D','头文字D'),
	@('Shutokou Battle','首都高赛车'), @('Tokyo Xtreme Racer','首都高赛车'),
	@('Kaido','街道赛车'),
	@('OutRun','OutRun四驱敞篷'),
	@('Sega Rally','世嘉拉力赛'),
	@('Colin McRae','科林麦克雷拉力'),
	@('V-Rally','V拉力赛'),
	@('World Rally Championship','世界拉力锦标赛'), @('WRC','世界拉力锦标赛'),
	@('NASCAR','NASCAR房车赛'),
	@('V8 Supercars','V8超级房车赛'),
	@('DTM Race','DTM德国房车赛'),
	@('TOCA','TOCA房车赛'),
	@('Ford Racing','福特赛车'),
	@('Mercedes-Benz','奔驰世界赛车'),
	@('Formula One','F1一级方程式'), @('F1 ','F1一级方程式'),
	@('Test Drive','Test Drive试驾'),
	@('18 Wheeler','18轮大卡车'),
	@('Crimson Sea','红海'),
	@('Rygar','阿尔戈斯战士'),
	@('Bujingai','武刃街'),
	@('Berserk','剑风传奇'),
	@('Dororo','多罗罗'), @('Blood Will Tell','多罗罗'),
	@('Hokuto no Ken','北斗神拳'), @('Fist of the North Star','北斗神拳'),
	@('Crimson Tears','血色之泪'),
	@('Mark of Kri','库里的印记'),
	@('Maximo','魔界村战士'),
	@('Ghouls','大魔界村'),
	@('Neo Contra','新魂斗罗'), @('Shattered Soldier','魂斗罗：破碎战士'),
	@('Dead to Rights','喋血双雄'),
	@('Kill.switch','绝杀开关'),
	@('Breakdown','崩溃'),
	@('Spawn','再生侠'),
	@('Valkyrie Profile','北欧女神'),
	@('Gallop Racer','骏马赛手'),
	@('Winning Post','胜利赛马'),
	@('G1 Jockey','G1职业骑师'),
	@('Derby Stallion','德比赛马'),
	@('Championship Manager','冠军足球经理'),
	@('International Superstar Soccer','国际超级足球'),
	@('This is Football','这就是足球'),
	@('World Soccer','世界足球'), #兜底(如WE变体)
	@('Kingdom Hearts II','王国之心2'),
	@('Kingdom Hearts','王国之心'),
	@('Final Fantasy X-2','最终幻想X-2'),
	@('Dirge of Cerberus','最终幻想VII：地狱犬的挽歌'),
	@('Ace Combat Zero','皇牌空战Zero'),
	@('Squadron Leader','皇牌空战5'),
	@('Ace Combat','皇牌空战'),
	@('Ace Combat 04','皇牌空战4'),
	@('Gran Turismo Concept','GT赛车概念版'),
	@('Jak and Daxter','杰克与达斯特'),
	@('Jak II','杰克与达斯特2'),
	@('Jak 3','杰克与达斯特3'),
	@('Jak X','杰克与达斯特X'),
	@('Kaitou Sly','狡狐大冒险'), @('Sly Cooper','狡狐大冒险'),
	@('Tales of Symphonia','交响乐传说'),
	@('Tales of Rebirth','重生传说'),
	@('Tales of Legendia','遗迹传说'),
	@('Tales of the Abyss','深渊传说'),
	@('Tales of Destiny','宿命传说'),
	@('Tales of Eternia','永恒传说'),
	@('Tales of Phantasia','幻想传说'),
	@('Tales of','传说系列'),
	@('Radiata Stories','拉迪亚塔战记'),
	@('Star Ocean','星之海洋'),
	@('Rogue Galaxy','银河游侠'),
	@('Shadow Hearts','影之心'),
	@('Growlanser','梦幻骑士'),
	@('Langrisser','梦幻模拟战'),
	@('Front Mission','前线任务'),
	@('Suikoden','幻想水浒传'),
	@('Wild ARMs','荒野兵器'), @('Wild Arms','荒野兵器'),
	@('Grandia','格兰蒂亚'),
	@('Dark Chronicle','暗黑编年史'),
	@('Dark Cloud','暗云'),
	@('Disgaea','魔界战记'),
	@('Atelier Iris','伊莉斯的炼金工房'), @('Iris no Atelier','伊莉斯的炼金工房'),
	@('Mana Khemia','玛娜的炼金术学院'), @('Mana-Khemia','玛娜的炼金术学院'),
	@('no Atelier','炼金工房'), @('Atelier','炼金工房'),
	@('Xenosaga','异度传说'),
	@('Breath of Fire','龙战士'),
	@('Makai Kingdom','魔界王国'),
	@('Phantom Brave','幻影冒险队'),
	@('La Pucelle','圣少女战记'),
	@('Generation of Chaos','混沌世代'),
	@('Sengoku Basara','战国BASARA'),
	@('Dynasty Tactics','三国志战记'), @('Sangokushi Senki','三国志战记'),
	@('Romance of the Three Kingdoms','三国志'),
	@('Sangokushi','三国志'),
	@('Nobunagas Ambition','信长之野望'), @('Nobunaga no Yabou','信长之野望'), @('Nobunaga','信长之野望'),
	@('Taikou Risshiden','太阁立志传'),
	@('Uncharted Waters','大航海时代'),
	@('Kessen','决战'),
	@('Jikkyou Powerful Pro Yakyuu','实况力量职业棒球'),
	@('Jikkyou Powerful','实况力量棒球'),
	@('Powerful Pro Yakyuu','实况力量职业棒球'),
	@('Minna no Golf','大众高尔夫'), @('Everybodys Golf','大众高尔夫'), @('Everybody s Golf','大众高尔夫'),
	@('Minna no Tennis','大众网球'), @('Everybodys Tennis','大众网球'), @('Everybody s Tennis','大众网球'),
	@('Minna no','大众系列'),
	@('Super Robot Wars','超级机器人大战'), @('Super Robot Taisen','超级机器人大战'),
	@('Another Century','王牌机战A.C.E.'),
	@('Gihren','基连的野望'),
	@('Kidou Senshi','机动战士高达'), @('Mobile Suit Gundam','机动战士高达'), @('MS Gundam','机动战士高达'),
	@('Gundam','高达'),
	@('SD Gundam','SD高达'),
	@('Armored Core','装甲核心'),
	@('NeoAngelique','新安杰莉可'),
	@('Neo Romance','新罗曼史'),
	@('My Merry','我的玛丽'),
	@('Memories Off','秋之回忆'),
	@('Infinity','无限之门'),
	@('12Riven','12Riven'),
	@('Princess Maker','美少女梦工厂'),
	@('Musou Orochi','无双大蛇'), @('Warriors Orochi','无双大蛇'), @('Orochi','无双大蛇'),
	@('Sengoku Musou','战国无双'), @('Samurai Warriors','战国无双'),
	@('Shin Sangoku Musou','真·三国无双'), @('Dynasty Warriors','真·三国无双'),
	@('Winning Eleven','实况足球'),
	@('Pro Evolution Soccer','实况足球'),
	@('FIFA','FIFA足球'),
	@('Madden','麦登橄榄球'),
	@('NFL','NFL橄榄球'),
	@('NBA Live','NBA Live篮球'), @('NBA Street','NBA街头篮球'), @('NBA 2K','NBA 2K篮球'), @('NBA','NBA篮球'),
	@('NHL','NHL冰球'),
	@('MLB','MLB棒球'),
	@('MVP Baseball','MVP棒球'),
	@('All-Star Baseball','全明星棒球'),
	@('Tiger Woods','老虎伍兹高尔夫'), @('PGA Tour','PGA高尔夫巡回赛'),
	@('Tony Hawk','托尼·霍克职业滑板'),
	@('Matt Hoffman','马特·霍夫曼BMX'), @('Dave Mirra','戴夫·米拉BMX'), @('BMX','BMX小轮车'),
	@('SSX','SSX极限滑雪'),
	@('Kelly Slater','凯利·斯莱特冲浪'),
	@('Shaun','肖恩·怀特滑雪'),
	@('Backyard','后院小伙伴'),
	@('Neopets','尼奥宠物'),
	@('Dragon Quest','勇者斗恶龙'),
	@('Final Fantasy','最终幻想'),
	@('Metal Gear Solid','合金装备'), @('Metal Gear','合金装备'),
	@('Devil May Cry','鬼泣'),
	@('God of War','战神'),
	@('Onimusha','鬼武者'), @('Shin Onimusha','新鬼武者'),
	@('Resident Evil','生化危机'), @('Biohazard','生化危机'), @('BioHazard','生化危机'),
	@('Silent Hill','寂静岭'),
	@('Fatal Frame','零'), @('Project Zero','零'),
	@('Tenchu','天诛'),
	@('Ratchet','瑞奇与叮当'),
	@('Crash','古惑狼'),
	@('Spyro','小龙斯派罗'),
	@('Sonic','索尼克'),
	@('Mega Man','洛克人'), @('Rockman','洛克人'),
	@('Castlevania','恶魔城'), @('Akumajou','恶魔城'),
	@('Tekken','铁拳'),
	@('Soul Calibur','刀魂'), @('SoulCalibur','刀魂'), @('Soulcalibur','刀魂'),
	@('Virtua Fighter','VR战士'),
	@('Dead or Alive','生死格斗'),
	@('Street Fighter','街头霸王'),
	@('King of Fighters','拳皇'),
	@('Guilty Gear','罪恶装备'),
	@('Samurai Spirits','侍魂'), @('Samurai Shodown','侍魂'),
	@('Darkstalkers','恶魔战士'), @('Vampire Darkstalkers','恶魔战士'),
	@('Bloody Roar','兽化格斗'),
	@('Mortal Kombat','真人快打'),
	@('Capcom vs SNK','卡普空对SNK'), @('SNK vs Capcom','SNK对卡普空'), @('SNK Vs','SNK对卡普空'),
	@('Marvel vs Capcom','漫威对卡普空'),
	@('Gran Turismo','GT赛车'),
	@('Need for Speed','极品飞车'),
	@('Ridge Racer','山脊赛车'),
	@('Burnout','横冲直撞'),
	@('Midnight Club','午夜俱乐部'),
	@('Wipeout','反重力赛车'), @('WipEout','反重力赛车'),
	@('Juiced','狂飙改装'),
	@('Street Racing Syndicate','街头赛车联盟'),
	@('Driver','车神'), @('Driv3r','车神3'),
	@('Call of Duty','使命召唤'),
	@('Medal of Honor','荣誉勋章'),
	@('SOCOM','海豹突击队'),
	@('TimeSplitters','时空分裂者'), @('Time Splitter','时空分裂者'),
	@('Conflict','冲突'),
	@('Conflict Desert','冲突：沙漠风暴'),
	@('Area 51','51区'),
	@('Black Hawk Down','黑鹰坠落'),
	@('Conflict Vietnam','冲突：越南'),
	@('Ghosthunter','捉鬼猎人'),
	@('Primal','原始兽'),
	@('Haven','哈文'),
	@('Kinetica','动力赛车'),
	@('Downhill','速降山地车'),
	@('War of the Monsters','怪兽大乱斗'),
	@('Auto Modellista','卡通赛车'),
	@('Cubix','酷比克斯'),
	@('Legion','军团'), #跳过类
	@('Titeuf','蒂托夫'),
	@('Asterix','阿斯特里克斯'),
	@('Tork','托克'),
	@('Whiplash','鞭打'),
	@('Scorpion King','蝎子王'),
	@('Xena','战士公主西娜'),
	@('Herdy','牧羊大冒险'),
	@('Tork','托克原始人'),
	@('I-Ninja','忍者小矮人'),
	@('Vexx','维克斯'),
	@('Voodoo Vince','巫毒文斯'),
	@('Malice','玛丽丝'),
	@('Tak','塔克'),
	@('Blinx','眨眼猫'),
	@('Ty','袋鼠泰'),
	@('Bionicle','生化战士'),
	@('Galerians','盖勒尼安'),
	@('Legaia','雷盖亚传说'),
	@('Okage','奥卡吉与影子王'),
	@('Tsugunai','赎罪'),
	@('Orphen','奥非尔的旅程'),
	@('Ephemeral Fantasia','幻想曲'),
	@('Evergrace','永恒的恩典'),
	@('Forever Kingdom','永恒王国'),
	@('Drakan','龙之结界'),
	@('Summoner','召唤师'),
	@('Sword of the Berserk','剑风传奇'),
	@('Koudelka','库德尔卡'),
	@('Azurik','阿祖里克'),
	@('Nightcaster','夜行者'),
	@('Baldur','博德之门'),
	@('Dungeon Explorer','地下城探索者'),
	@('Gauntlet','魔窟寻宝'),
	@('Bards Tale','吟游诗人'),
	@('Champions','诺拉斯勇士'),
	@('Bomberman','炸弹人'),
	@('Bomb','炸弹人'), #兜底
	@('Worms','百战天虫'),
	@('Chess','国际象棋'),
	@('Solitaire','纸牌'),
	@('Mahjong','麻将'),
	@('Shogi','将棋'),
	@('Hanafuda','花札'),
	@('Pachinko','柏青哥'),
	@('Pachi-Slot','柏青嫂'),
	@('Slot','老虎机'),
	@('Casino','赌场游戏'),
	@('Ultraman','奥特曼'),
	@('Kamen Rider','假面骑士'),
	@('Super Sentai','超级战队'),
	@('Power Rangers','恐龙战队'),
	@('Godzilla','哥斯拉'),
	@('King Kong','金刚'),
	@('Jaws','大白鲨'),
	@('Predator','铁血战士'),
	@('Alien vs','异形大战'),
	@('Alien','异形'),
	@('Robocop','机械战警'),
	@('Spawn','再生侠'),
	@('Blade','刀锋战士'),
	@('Hellboy','地狱男爵'),
	@('Constantine','康斯坦丁'),
	@('Catwoman','猫女'),
	@('Elektra','艾丽卡'),
	@('Fantastic Four','神奇四侠'),
	@('Incredible Hulk','绿巨人'),
	@('Punisher','惩罚者'),
	@('Blade','刀锋战士'),
	@('Underworld','黑夜传说'),
	@('Van Helsing','范海辛'),
	@('Resident','生化危机'), #兜底
	@('Simple 2000','Simple 2000廉价游戏'),
	@('D3 Publisher','D3廉价游戏'),
	@('Oretachi','街机复古合集'),
	@('Taito Memories','taito街机怀旧'),
	@('Taito Legends','taito街机怀旧'),
	@('Capcom Classics','卡普空街机怀旧'),
	@('Namco Museum','南梦宫博物馆'),
	@('Sega Classic','世嘉街机怀旧'),
	@('Midway Arcade','Midway街机怀旧'),
	@('Intellivision','Intellivision怀旧'),
	@('Atari Anthology','雅达利怀旧合集'),
	@('Arcade','街机合集'),
	@('PopCap','宝开小游戏'),
	@('Zuma','祖玛'),
	@('Bejeweled','宝石迷阵'),
	@('Peggle','幻幻球'),
	@('Bookworm','图书管理员'),
	@('Chuzzle','毛毛球'),
	@('Insaniquarium','疯狂水族馆'),
	@('Feeding Frenzy','吞食鱼'),
	@('Heavy Weapon','重装武器'),
	@('Rocket Mania','火箭狂欢'),
	@('Typer Shark','打字鲨鱼'),
	@('Hamsterball','仓鼠球'),
	@('NFS','极品飞车'),
	@('GTA','侠盗猎车手'),
	@('Grand Theft Auto','侠盗猎车手')
)

#========== 第2层:系列关键词(命中后拼接 副标题/序号) ==========
$series = @(
	@('Final Fantasy','最终幻想'),
	@('Dragon Quest','勇者斗恶龙'),
	@('Kingdom Hearts','王国之心'),
	@('Metal Gear Solid','合金装备'), @('Metal Gear','合金装备'),
	@('Devil May Cry','鬼泣'),
	@('God of War','战神'),
	@('Onimusha','鬼武者'),
	@('Shin Onimusha','新鬼武者'),
	@('Resident Evil','生化危机'),
	@('Biohazard','生化危机'),
	@('BioHazard','生化危机'),
	@('Silent Hill','寂静岭'),
	@('Fatal Frame','零'),
	@('Project Zero','零'),
	@('Tenchu','天诛'),
	@('Tekken','铁拳'),
	@('Soul Calibur','刀魂'),
	@('SoulCalibur','刀魂'),
	@('Soulcalibur','刀魂'),
	@('Virtua Fighter','VR战士'),
	@('Dead or Alive','生死格斗'),
	@('Street Fighter','街头霸王'),
	@('King of Fighters','拳皇'),
	@('Guilty Gear','罪恶装备'),
	@('Samurai Spirits','侍魂'),
	@('Samurai Shodown','侍魂'),
	@('Darkstalkers','恶魔战士'),
	@('Vampire Darkstalkers','恶魔战士'),
	@('Bloody Roar','兽化格斗'),
	@('Mortal Kombat','真人快打'),
	@('Capcom vs SNK','卡普空对SNK'),
	@('SNK vs Capcom','SNK对卡普空'),
	@('Marvel vs Capcom','漫威对卡普空'),
	@('Ratchet','瑞奇与叮当'),
	@('Jak and Daxter','杰克与达斯特'),
	@('Crash','古惑狼'),
	@('Spyro','小龙斯派罗'),
	@('Sonic','索尼克'),
	@('Mega Man','洛克人'),
	@('Rockman','洛克人'),
	@('Castlevania','恶魔城'),
	@('Akumajou Dracula','恶魔城'),
	@('Prince of Persia','波斯王子'),
	@('Tomb Raider','古墓丽影'),
	@('Splinter Cell','分裂细胞'),
	@('Hitman','终极刺客'),
	@('Max Payne','马克思·佩恩'),
	@('Grand Theft Auto','侠盗猎车手'),
	@('GTA','侠盗猎车手'),
	@('True Crime','真实犯罪'),
	@('The Getaway','伦敦黑帮'),
	@('Driv3r','车神3'),
	@('Driver','车神'),
	@('Stuntman','特技车手'),
	@('Manhunt','侠盗猎魔'),
	@('Bully','恶霸鲁尼'),
	@('Red Dead','荒野大镖客'),
	@('Gungrave','铳墓'),
	@('Killzone','杀戮地带'),
	@('SOCOM','海豹突击队'),
	@('Call of Duty','使命召唤'),
	@('Medal of Honor','荣誉勋章'),
	@('TimeSplitters','时空分裂者'),
	@('Time Splitter','时空分裂者'),
	@('Time Crisis','时间危机'),
	@('Crisis Zone','时间危机：危机地带'),
	@('Ghost Recon','幽灵行动'),
	@('Rainbow Six','彩虹六号'),
	@('Conflict','冲突'),
	@('Freedom Fighters','自由战士'),
	@('Half-Life','半条命'),
	@('Red Faction','红色派系'),
	@('Quake','雷神之锤'),
	@('Unreal','虚幻竞技场'),
	@('Serious Sam','英雄萨姆'),
	@('GoldenEye','黄金眼'),
	@('James Bond','007系列'),
	@('Nightfire','007：夜火'),
	@('Agent Under Fire','007：特工在行动'),
	@('Gran Turismo','GT赛车'),
	@('Need for Speed','极品飞车'),
	@('NFS','极品飞车'),
	@('Ridge Racer','山脊赛车'),
	@('Burnout','横冲直撞'),
	@('Midnight Club','午夜俱乐部'),
	@('Wipeout','反重力赛车'),
	@('WipEout','反重力赛车'),
	@('Ridge','山脊赛车'),
	@('Initial D','头文字D'),
	@('Shutokou Battle','首都高赛车'),
	@('Tokyo Xtreme Racer','首都高赛车'),
	@('Kaido','街道赛车'),
	@('OutRun','OutRun四驱敞篷'),
	@('Sega Rally','世嘉拉力赛'),
	@('Colin McRae','科林麦克雷拉力'),
	@('V-Rally','V拉力赛'),
	@('World Rally Championship','世界拉力锦标赛'),
	@('WRC','世界拉力锦标赛'),
	@('NASCAR','NASCAR房车赛'),
	@('V8 Supercars','V8超级房车赛'),
	@('DTM Race','DTM德国房车赛'),
	@('TOCA','TOCA房车赛'),
	@('Race Driver','TOCA赛车'),
	@('F1 ','F1一级方程式'),
	@('Formula One','F1一级方程式'),
	@('Crazy Taxi','疯狂出租车'),
	@('18 Wheeler','18轮大卡车'),
	@('Alpine Racer','高山滑雪'),
	@('ATV Offroad','ATV全地形车'),
	@('MX vs','MX对ATV越野摩托'),
	@('Winning Eleven','实况足球'),
	@('Pro Evolution Soccer','实况足球'),
	@('World Soccer Winning Eleven','实况足球'),
	@('FIFA','FIFA足球'),
	@('Madden','麦登橄榄球'),
	@('NFL Street','NFL街头橄榄球'),
	@('NFL','NFL橄榄球'),
	@('NBA Live','NBA Live篮球'),
	@('NBA Street','NBA街头篮球'),
	@('NBA 2K','NBA 2K篮球'),
	@('NBA','NBA篮球'),
	@('NHL','NHL冰球'),
	@('MLB','MLB棒球'),
	@('MVP Baseball','MVP棒球'),
	@('All-Star Baseball','全明星棒球'),
	@('Tiger Woods','老虎伍兹高尔夫'),
	@('PGA Tour','PGA高尔夫巡回赛'),
	@('Minna no Golf','大众高尔夫'),
	@('Everybodys Golf','大众高尔夫'),
	@('Everybody s Golf','大众高尔夫'),
	@('Minna no Tennis','大众网球'),
	@('Everybodys Tennis','大众网球'),
	@('Everybody s Tennis','大众网球'),
	@('Tony Hawk','托尼·霍克职业滑板'),
	@('SSX','SSX极限滑雪'),
	@('Jikkyou Powerful Pro Yakyuu','实况力量职业棒球'),
	@('Jikkyou Powerful','实况力量棒球'),
	@('Powerful Pro Yakyuu','实况力量职业棒球'),
	@('Winning Post','胜利赛马'),
	@('Gallop Racer','骏马赛手'),
	@('Derby Stallion','德比赛马'),
	@('Championship Manager','冠军足球经理'),
	@('International Superstar Soccer','国际超级足球'),
	@('This is Football','这就是足球'),
	@('Super Robot Wars','超级机器人大战'),
	@('Super Robot Taisen','超级机器人大战'),
	@('Another Century','王牌机战A.C.E.'),
	@('Gundam','高达'),
	@('Kidou Senshi','机动战士高达'),
	@('Mobile Suit Gundam','机动战士高达'),
	@('SD Gundam','SD高达'),
	@('Gihren','基连的野望'),
	@('Macross','超时空要塞'),
	@('Armored Core','装甲核心'),
	@('Front Mission','前线任务'),
	@('Zoids','索斯机械兽'),
	@('Sengoku Basara','战国BASARA'),
	@('Shin Sangoku Musou','真·三国无双'),
	@('Dynasty Warriors','真·三国无双'),
	@('Sengoku Musou','战国无双'),
	@('Samurai Warriors','战国无双'),
	@('Musou Orochi','无双大蛇'),
	@('Warriors Orochi','无双大蛇'),
	@('Orochi','无双大蛇'),
	@('Dynasty Tactics','三国志战记'),
	@('Sangokushi Senki','三国志战记'),
	@('Romance of the Three Kingdoms','三国志'),
	@('Sangokushi','三国志'),
	@('Nobunagas Ambition','信长之野望'),
	@('Nobunaga no Yabou','信长之野望'),
	@('Nobunaga','信长之野望'),
	@('Taikou Risshiden','太阁立志传'),
	@('Uncharted Waters','大航海时代'),
	@('Kessen','决战'),
	@('Winning Eleven','实况足球'),
	@('Valkyrie Profile','北欧女神'),
	@('Star Ocean','星之海洋'),
	@('Suikoden','幻想水浒传'),
	@('Wild ARMs','荒野兵器'),
	@('Wild Arms','荒野兵器'),
	@('Grandia','格兰蒂亚'),
	@('Dark Cloud','暗云'),
	@('Dark Chronicle','暗黑编年史'),
	@('Rogue Galaxy','银河游侠'),
	@('Radiata Stories','拉迪亚塔战记'),
	@('Shadow Hearts','影之心'),
	@('Growlanser','梦幻骑士'),
	@('Langrisser','梦幻模拟战'),
	@('Xenosaga','异度传说'),
	@('Breath of Fire','龙战士'),
	@('Disgaea','魔界战记'),
	@('Atelier Iris','伊莉斯的炼金工房'),
	@('Iris no Atelier','伊莉斯的炼金工房'),
	@('Mana Khemia','玛娜的炼金术学院'),
	@('Mana-Khemia','玛娜的炼金术学院'),
	@('no Atelier','炼金工房'),
	@('Atelier','炼金工房'),
	@('Romancing SaGa','浪漫沙加'),
	@('Unlimited Saga','无限沙加'),
	@('Shin Megami Tensei','真·女神转生'),
	@('Persona','女神异闻录'),
	@('Digital Devil Saga','数码恶魔传说'),
	@('Devil Summoner','恶魔召唤师'),
	@("King's Field",'国王密令'),
	@('EverQuest','无尽的任务'),
	@("Baldur's Gate",'博德之门'),
	@('Baldur','博德之门'),
	@('Champions of Norrath','诺拉斯勇士'),
	@('Champions','诺拉斯勇士'),
	@('Gauntlet','魔窟寻宝'),
	@('Dungeon Explorer','地下城探索者'),
	@('The Sims','模拟人生'),
	@('SimCity','模拟城市'),
	@('A-Train','A列车'),
	@('Densha de Go','电车GO'),
	@('Taiko no Tatsujin','太鼓达人'),
	@('Guitar Hero','吉他英雄'),
	@('Dance Dance Revolution','DDR跳舞机'),
	@('DDR','DDR跳舞机'),
	@('Karaoke Revolution','卡拉OK革命'),
	@('GuitarFreaks','吉他高手'),
	@('DrumMania','鼓手高手'),
	@('beatmania','beatmania打拍机'),
	@('IIDX','beatmania IIDX'),
	@('Popn Music','波普音乐'), @("Pop'n Music",'波普音乐'),
	@('EyeToy','EyeToy体感游戏'),
	@('SingStar','SingStar歌星'),
	@('Buzz!','Buzz智力问答'),
	@('Katamari','块魂'),
	@('Minna Daisuki Katamari','我们爱块魂'),
	@('Tales of','传说系列'),
	@('Tales of Symphonia','交响乐传说'),
	@('Tales of Rebirth','重生传说'),
	@('Tales of Legendia','遗迹传说'),
	@('Tales of the Abyss','深渊传说'),
	@('Tales of Destiny','宿命传说'),
	@('Tales of Eternia','永恒传说'),
	@('Tales of Phantasia','幻想传说'),
	@('Harvest Moon','牧场物语'),
	@('Monster Rancher','怪物农场'),
	@('Digimon','数码宝贝'),
	@('Chocobo','陆行鸟'),
	@('Itadaki Street','富豪街'),
	@('Tokimeki','心跳回忆'),
	@('To Heart','To Heart'),
	@('ToHeart','To Heart'),
	@('Clannad','CLANNAD'),
	@('Little Busters','Little Busters'),
	@('Higurashi','寒蝉鸣泣之时'),
	@('Suzumiya Haruhi','凉宫春日'),
	@('Lucky Star','幸运星'),
	@('Memories Off','秋之回忆'),
	@('Yoake mae yori ruriiro na','夜明前的琉璃色'),
	@('Hiiro no Kakera','绯色碎片'),
	@('Harukanaru Toki no Naka de','遥远时空中'),
	@('Angelique','安杰莉可'),
	@('Princess Maker','美少女梦工厂'),
	@('Doko Demo Issho','随身玩伴·多罗猫'),
	@('Dokodemo Issyo','随身玩伴·多罗猫'),
	@('Boku no Natsuyasumi','我的暑假'),
	@('Natsuyasumi','我的暑假'),
	@('Saru! Get You','捉猴啦'),
	@('Saru Battle','捉猴啦'),
	@('Piposaru','捉猴啦'),
	@('Ape Escape','捉猴啦'),
	@('I.Q Remix','智能方块'),
	@('Intelligent Qube','智能方块'),
	@('Bomberman','炸弹人'),
	@('Puyo Puyo','魔法气泡'),
	@('Ikaruga','斑鸠'),
	@('Gradius','宇宙巡航机'),
	@('R-Type','R-Type纵向射击'),
	@('Shikigami no Shiro','式神之城'),
	@('Castle Shikigami','式神之城'),
	@('Contra','魂斗罗'),
	@('Metal Slug','合金弹头'),
	@('Fatal Fury','饿狼传说'),
	@('Garou','饿狼传说：狼之印记'),
	@('Art of Fighting','龙虎之拳'),
	@('The Last Blade','月华剑士'),
	@('Viewtiful Joe','红侠乔伊'),
	@('Killer 7','杀手7'),
	@('Chaos Legion','混沌军团'),
	@('Clock Tower','时钟塔'),
	@('Haunting Ground','狂气古城'),
	@('Demento','狂气古城'),
	@('Twisted Metal','烈火战车'),
	@('Destruction Derby','毁灭德比'),
	@('Rygar','阿尔戈斯战士'),
	@('Bujingai','武刃街'),
	@('Berserk','剑风传奇'),
	@('Dororo','多罗罗'),
	@('Blood Will Tell','多罗罗'),
	@('Hokuto no Ken','北斗神拳'),
	@('Fist of the North Star','北斗神拳'),
	@('Kuon','九怨'),
	@('Rule of Rose','蔷薇法则'),
	@('The Suffering','苦难'),
	@('Siren','死魂曲'),
	@('Forbidden Siren','死魂曲'),
	@('Way of the Samurai','武士道'),
	@('Shinobi','忍·Shinobi'),
	@('Otogi','御伽'),
	@('Genji','源氏'),
	@('God Hand','上帝之手'),
	@('Odin Sphere','奥丁领域'),
	@('The Bouncer','神佑擂手'),
	@('Zettai Zetsumei Toshi','绝体绝命都市'),
	@('Disaster Report','绝体绝命都市'),
	@('Crimson Sea','红海'),
	@('Klonoa','风之克罗诺亚'),
	@('Mr. Driller','钻地先生'),
	@('Point Blank','点空白'),
	@('House of the Dead','死亡之屋'),
	@('Vampire Night','吸血鬼之夜'),
	@('Time Splitters','时空分裂者'),
	@('Neo Contra','新魂斗罗'),
	@('Shattered Soldier','魂斗罗：破碎战士'),
	@('Dead to Rights','喋血双雄'),
	@('Breakdown','崩溃'),
	@('Spawn','再生侠'),
	@('Mark of Kri','库里的印记'),
	@('Maximo','魔界村战士'),
	@('Ghouls','大魔界村'),
	@('Musashi','武藏传'),
	@('Drakengard','龙背上的骑兵'),
	@('Okage','奥卡吉与影子王'),
	@('Tsugunai','赎罪'),
	@('Orphen','奥非尔的旅程'),
	@('Ephemeral Fantasia','幻想曲'),
	@('Evergrace','永恒的恩典'),
	@('Forever Kingdom','永恒王国'),
	@('Drakan','龙之结界'),
	@('Summoner','召唤师'),
	@('Koudelka','库德尔卡'),
	@('Legaia','雷盖亚传说'),
	@('Galerians','盖勒尼安'),
	@('Ultraman','奥特曼'),
	@('Kamen Rider','假面骑士'),
	@('Super Sentai','超级战队'),
	@('Power Rangers','恐龙战队'),
	@('Godzilla','哥斯拉'),
	@('Robocop','机械战警'),
	@('Predator','铁血战士'),
	@('Alien vs','异形大战'),
	@('Alien','异形'),
	@('Star Wars','星球大战'),
	@('Lord of the Rings','指环王'),
	@('The Two Towers','指环王：双塔奇兵'),
	@('Return of the King','指环王：王者归来'),
	@('Harry Potter','哈利·波特'),
	@('Spider-Man','蜘蛛侠'),
	@('Spider Man','蜘蛛侠'),
	@('Batman','蝙蝠侠'),
	@('X-Men','X战警'),
	@('The Punisher','惩罚者'),
	@('Punisher','惩罚者'),
	@('Fantastic Four','神奇四侠'),
	@('Incredible Hulk','绿巨人'),
	@('Hellboy','地狱男爵'),
	@('Catwoman','猫女'),
	@('Elektra','艾丽卡'),
	@('Van Helsing','范海辛'),
	@('Blade','刀锋战士'),
	@('Underworld','黑夜传说'),
	@('Constantine','康斯坦丁'),
	@('Scorpion King','蝎子王'),
	@('Terminator','终结者'),
	@('Transformers','变形金刚'),
	@('Mission: Impossible','碟中谍'),
	@('Mission Impossible','碟中谍'),
	@('James Bond','007系列'),
	@('Matrix','黑客帝国'),
	@('Enter the Matrix','黑客帝国：进入矩阵'),
	@('Naruto','火影忍者'),
	@('Bleach','死神'),
	@('One Piece','海贼王'),
	@('Dragon Ball','龙珠'),
	@('Dragonball','龙珠'),
	@('Inuyasha','犬夜叉'),
	@('InuYasha','犬夜叉'),
	@('Rurouni Kenshin','浪客剑心'),
	@('Yu Yu Hakusho','幽游白书'),
	@('Yu-Gi-Oh','游戏王'),
	@('Zatch Bell','金色卡修'),
	@('Gashbell','金色卡修'),
	@('Konjiki no Gash','金色卡修'),
	@('D.Gray-man','驱魔少年'),
	@('Detective Conan','名侦探柯南'),
	@('Meitantei Conan','名侦探柯南'),
	@('Evangelion','新世纪福音战士'),
	@('Neon Genesis Evangelion','新世纪福音战士'),
	@('Code Geass','叛逆的鲁鲁修'),
	@('Eureka Seven','交响诗篇'),
	@('Fullmetal Alchemist','钢之炼金术师'),
	@('Full Metal Alchemist','钢之炼金术师'),
	@('Hagane no Renkinjutsushi','钢之炼金术师'),
	@('Sakura Taisen','樱花大战'),
	@('Sakura War','樱花大战'),
	@('Macross','超时空要塞'),
	@('Namco Museum','南梦宫博物馆'),
	@('Capcom Classics','卡普空街机怀旧'),
	@('Taito Memories','taito街机怀旧'),
	@('Taito Legends','taito街机怀旧'),
	@('Midway Arcade','Midway街机怀旧'),
	@('Atari Anthology','雅达利怀旧合集'),
	@('Oretachi','街机复古合集'),
	@('Worms','百战天虫'),
	@('Pachinko','柏青哥'),
	@('Pachi-Slot','柏青嫂'),
	@('Jissen Pachi','实战柏青嫂'),
	@('Slot','老虎机'),
	@('Mahjong','麻将'),
	@('Shogi','将棋'),
	@('Hanafuda','花札'),
	@('Casino','赌场游戏'),
	@('UFC','UFC终极格斗'),
	@('K-1','K-1格斗'),
	@('K1 ','K-1格斗'),
	@('WWE','WWE美式摔角'),
	@('SmackDown','WWE SmackDown'),
	@('Def Jam','Def Jam嘻哈格斗'),
	@('Rumble Roses','摔角玫瑰'),
	@('All Star Pro-Wrestling','全明星职业摔角'),
	@('Kinnikuman','金肉人'),
	@('Goemon','大盗五右卫门'),
	@('Lunar','露娜传说'),
	@('PopCap','宝开小游戏'),
	@('Zuma','祖玛'),
	@('Bejeweled','宝石迷阵'),
	@('Ty ','袋鼠泰'),
	@('Tak','塔克'),
	@('Bionicle','生化战士'),
	@('Neopets','尼奥宠物'),
	@('Backyard','后院小伙伴'),
	@('Cubix','酷比克斯'),
	@('Vexx','维克斯'),
	@('Voodoo Vince','巫毒文斯'),
	@('Malice','玛丽丝'),
	@('I-Ninja','忍者小矮人'),
	@('Whiplash','鞭打'),
	@('Tork','托克'),
	@('Herdy','牧羊大冒险'),
	@('Haven','哈文'),
	@('Kinetica','动力赛车'),
	@('Downhill','速降山地车'),
	@('War of the Monsters','怪兽大乱斗'),
	@('Auto Modellista','卡通赛车'),
	@('Primal','原始兽'),
	@('Ghosthunter','捉鬼猎人'),
	@('Area 51','51区'),
	@('Black Hawk Down','黑鹰坠落'),
	@('Galleon','大帆船冒险'),
	@('XIII','XIII杀手'),
	@('Kya','卡雅传奇'),
	@('Voodoo','巫毒'),
	@('Blinx','眨眼猫'),
	@('Tork','托克'),
	@('Asterix','阿斯特里克斯'),
	@('Titeuf','蒂托夫'),
	@('Xena','战士公主西娜'),
	@('Legion','军团'),
	@('Splashdown','水上摩托'),
	@('Sno-Cross','雪地摩托'),
	@('Sled Storm','雪地风暴'),
	@('Kelly Slater','凯利·斯莱特冲浪'),
	@('Shaun','肖恩·怀特滑雪'),
	@('Matt Hoffman','马特·霍夫曼BMX'),
	@('Dave Mirra','戴夫·米拉BMX'),
	@('BMX','BMX小轮车'),
	@('Ford Racing','福特赛车'),
	@('Mercedes-Benz','奔驰世界赛车'),
	@('Test Drive','Test Drive试驾'),
	@('Juiced','狂飙改装'),
	@('Street Racing Syndicate','街头赛车联盟'),
	@('Midnight Club','午夜俱乐部'),
	@('NHL','NHL冰球')
)

#========== 第3层:副标题短语(系列命中后,与序号一起拼接) ==========
$subs = @(
	@('Sons of Liberty','自由之子'),
	@('Snake Eater','食蛇者'),
	@('Substance','实体版'),
	@('Subsistence','生存版'),
	@('San Andreas','圣安地列斯'),
	@('Vice City','罪恶都市'),
	@('Liberty City','自由城'),
	@('Dantes Awakening','但丁的觉醒'),
	@('Wrath of Heaven','天之怒'),
	@('Fatal Shadows','致命暗影'),
	@('Kurenai','红'),
	@('Crimson Butterfly','红蝶'),
	@('Tormented','刺青之声'),
	@('Ultimate Ninja','终极忍者'),
	@('Uzumaki','漩涡忍传'),
	@('Grand Battle','激斗大会'),
	@('Grand Adventure','大冒险'),
	@('Budokai Tenkaichi','天下一武道会'),
	@('Budokai','武道会'),
	@('Frontline','前线'),
	@('Rising Sun','旭日'),
	@('European Assault','欧洲战场'),
	@('Pacific Assault','太平洋战场'),
	@('Finest Hour','最辉煌的时刻'),
	@('Big Red One','大红一师'),
	@('Hot Pursuit','热力追踪'),
	@('Underground','地下狂飙'),
	@('Most Wanted','最高通缉'),
	@('Carbon','卡本峡谷'),
	@('Porsche Unleashed','保时捷之旅'),
	@('Point of Impact','撞击点'),
	@('Takedown','大冲撞'),
	@('Revenge','复仇'),
	@('DUB Edition','DUB版'),
	@('Tag Tournament','TAG'),
	@('Final Mix','最终混合版'),
	@('Empires','帝国'),
	@('Moushouden','猛将传'),
	@('Xtreme Legends','猛将传'),
	@('International','国际版'),
	@('Directors Cut','导演剪辑版'),
	@('Kanzenhan','完全版'),
	@('Gaiden','外传'),
	@('Outbreak','爆发'),
	@('Dead Aim','死亡目标'),
	@('Gun Survivor','枪下游魂'),
	@('Code Veronica','圣女之战'),
	@('Veronica','圣女之战'),
	@('Alpha 2nd','α2'),
	@('Alpha','α'),
	@('IMPACT','IMPACT'),
	@('Original Generations','OG'),
	@('Original Generation','OG'),
	@('Precursor Legacy','先驱的遗产'),
	@('Nitro Kart','狂飙赛车'),
	@('Twinsanity','双胞胎狂想曲'),
	@('Enter the Dragonfly','龙之飞翔'),
	@('A Heros Tale','英雄传说'),
	@('The Eternal Night','永恒之夜'),
	@('Wrath of Cortex','怒之军团'),
	@('Tricky','Tricky'),
	@('Prologue','序曲'),
	@('Concept','概念版'),
	@('A-spec','A-spec'),
	@('Girls Side','女生版'),
	@('Federation vs Zeon','联邦vs吉恩'),
	@('AEUG vs Titans','奥古vs泰坦斯'),
	@('Desert Storm','沙漠风暴'),
	@('Vietnam','越南'),
	@('The Room','房间'),
	@('Lament of Innocence','无罪的叹息'),
	@('Curse of Darkness','暗之诅咒'),
	@('Yami no Juin','暗之咒印'),
	@('Dawn of Dreams','梦之黎明'),
	@('Nocturne','夜曲'),
	@('Lucifers Call','路西法之召唤'),
	@('Till the End of Time','直到时光尽头'),
	@('Directors','导演剪辑版'),
	@('Eternal Mana','永恒玛娜'),
	@('The Azoth of Destiny','命运的水银'),
	@('Millennium Falcon','千年之鹰'),
	@('Silmeria','西尔梅莉亚'),
	@('Samurais Destiny','武士的命运'),
	@('Warriors of the Lost','失落的战士'),
	@('The Unsung War','无名的战争'),
	@('The Belkan War','贝尔卡战争'),
	@('Squadron Leader','中队长'),
	@('Advent Children','降临之子'),
	@('Sword of Seals','封印之剑'),
	@('Sacred Stones','圣魔光石'),
	@('Festival of Hunters','猎人之祭'),
	@('American Wasteland','美国废土'),
	@('Underground 2','地下狂飙2'),
	@('Sk8land','滑板乐园'),
	@('DJ','DJ版'),
	@('Project 8','第8号计划'),
	@('Proving Ground','试炼之地'),
	@('Wasteland','废土'),
	@('Tony Hawks American Sk8land','美国滑板乐园'),
	@('Nemesis','复仇女神'),
	@('Regeneration','重生'),
	@('Apocalypse','天启'),
	@('Reloaded','重装上阵'),
	@('Uprising','起义'),
	@('Evolution','进化版')
)

#========== 构建编译好的正则(按关键词长度降序,保证最长优先;含词边界防误伤) ==========
function Build-Matcher($pairs) {
	$sorted = $pairs | Sort-Object { $_[0].Length } -Descending
	$map = @{}
	foreach ($p in $sorted) { $map[$p[0].ToLowerInvariant()] = $p[1] }
	$alt = ($sorted | ForEach-Object {
		$e = [regex]::Escape($_[0])
		if ($_[0][0]  -match '[A-Za-z0-9]') { $e = '\b' + $e }
		if ($_[-1][-1] -match '[A-Za-z0-9]') { $e = $e + '\b' }
		$e
	}) -join '|'
	$opts = [System.Text.RegularExpressions.RegexOptions]'IgnoreCase, Compiled'
	$rx = New-Object System.Text.RegularExpressions.Regex("(?:$alt)", $opts)
	return @{ Rx = $rx; Map = $map }
}
#系列性条目必须走 series 流程(自动拼接序号/副标题),从 exact 层剔除,
#exact 只保留独立游戏与序号歧义修复条目(如 Kingdom Hearts II → 王国之心2)。
$seriesKeys = @{}
foreach ($p in $series) { $seriesKeys[$p[0].ToLowerInvariant()] = $true }
$exact = $exact | Where-Object { -not $seriesKeys.ContainsKey($_[0].ToLowerInvariant()) }
$Ex = Build-Matcher $exact
$Se = Build-Matcher $series
$Su = Build-Matcher $subs

$rxSerial = New-Object System.Text.RegularExpressions.Regex('^([A-Z0-9]{4})[_.](\d{3})[._](\d{2})$')
$rxArabic = New-Object System.Text.RegularExpressions.Regex('\b(\d{1,4})\b', [System.Text.RegularExpressions.RegexOptions]::Compiled)
$rxRoman  = New-Object System.Text.RegularExpressions.Regex('\b(XX|XIII|XII|XI|X|IX|VIII|VII|VI|IV|V|III|II)\b(?![-\w])', [System.Text.RegularExpressions.RegexOptions]::Compiled)

#========== 主循环:解析 CSV,翻译,去重 ==========
$result = New-Object 'System.Collections.Generic.SortedDictionary[string,string]'
$total = 0; $hit = 0; $skipped = 0
foreach ($line in [System.IO.File]::ReadLines($csvPath)) {
	if ([string]::IsNullOrWhiteSpace($line)) { continue }
	$total++
	$idx = $line.IndexOf(';')
	if ($idx -lt 1) { continue }
	$serial = $line.Substring(0, $idx)
	$title = $line.Substring($idx + 1)
	$m = $rxSerial.Match($serial)
	if (-not $m.Success) { $skipped++; continue }
	$code = $m.Groups[1].Value + '-' + $m.Groups[2].Value + $m.Groups[3].Value
	if ($result.ContainsKey($code)) { continue }  #同 code 只保留第一条

	$cn = $null
	#第1层:精确短语
	$em = $Ex.Rx.Match($title)
	if ($em.Success) {
		$cn = $Ex.Map[$em.Value.ToLowerInvariant()]
	} else {
		#第2层:系列
		$sm = $Se.Rx.Match($title)
		if ($sm.Success) {
			$s = $Se.Map[$sm.Value.ToLowerInvariant()]
			#副标题:取所有命中里最长的短语(如 Project Zero 2 - Crimson Butterfly
			#同时命中 Zero 与 Crimson Butterfly,应取更具体的后者)
			$u = $null
			$best = 0
			foreach ($mm in $Su.Rx.Matches($title)) {
				if ($mm.Value.Length -gt $best) { $best = $mm.Value.Length; $u = $Su.Map[$mm.Value.ToLowerInvariant()] }
			}
			#序号(阿拉伯优先;副标题存在时仅附加阿拉伯,避免 CVX 的 X 之类误判)
			$num = $null; $roman = $null
			$am = $rxArabic.Match($title)
			if ($am.Success) { $num = ([int]$am.Groups[1].Value).ToString() }
			if ($u) {
				if ($num) { $cn = "$s$num`：$u" } else { $cn = "$s`：$u" }
			} else {
				if (-not $num) {
					$rm = $rxRoman.Match($title)
					if ($rm.Success) { $roman = $rm.Groups[1].Value }
				}
				if ($num) { $cn = "$s$num" }
				elseif ($roman) { $cn = "$s$roman" }
				else { $cn = $s }
			}
		}
	}
	if ($cn) { $result[$code] = $cn; $hit++ }
}

#========== 输出头文件(UTF-8 无 BOM,ASCII 序即 SortedDictionary 默认) ==========
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('//自动生成文件,勿手改!由 make_game_titles_cn.ps1 从 gamename.csv(PS2游戏ID数据库)')
[void]$sb.AppendLine('//生成:产品代码→简体中文标题,按 code ASCII 序排列(lookupCNTitle 二分查找依赖此顺序)。')
[void]$sb.AppendLine("//生成时间: $(Get-Date -Format 'yyyy-MM-dd HH:mm')  条目数: $($result.Count)/$total (跳过无译名 $skipped 行)")
foreach ($kv in $result.GetEnumerator()) {
	[void]$sb.AppendLine("{`"$($kv.Key)`", `"$($kv.Value)`"},")
}
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), $utf8NoBom)

Write-Host "总行: $total  命中翻译: $hit  输出条目: $($result.Count)  跳过: $($skipped)"
Write-Host "输出: $outPath"
Write-Host ""
Write-Host "=== 随机抽样 30 条 ==="
$result.GetEnumerator() | Get-Random -Count ([Math]::Min(30, $result.Count)) | Sort-Object Name | ForEach-Object { "  $($_.Key) -> $($_.Value)" }
