# Generate src/gbk_table.c - GB2312 (GBK subset) double-byte -> Unicode mapping
# Used to repair filenames written as fake-UTF-16 (GBK bytes widened to 16-bit)
# by legacy tools. Sorted by GBK code; lookup via binary search.
$rootPath = 'd:\wLaunchELF_R3Z-master'
$outPath = Join-Path $rootPath 'src\gbk_table.c'

$enc = [System.Text.Encoding]::GetEncoding(936)
$entries = New-Object System.Collections.Generic.List[string]
$pairs = New-Object System.Collections.Generic.List[object]

foreach ($hi in 0xA1..0xF7) {
    foreach ($lo in 0xA1..0xFE) {
        $bytes = [byte[]]@($hi, $lo)
        $s = $enc.GetString($bytes)
        if ($s.Length -ne 1) { continue }
        $ch = $s[0]
        $uni = [int]$ch
        # skip ASCII-mapped positions; keep real CJK/symbol glyphs
        if ($uni -lt 0x80) { continue }
        # roundtrip: this GBK position really maps to this Unicode char
        $rt = $enc.GetBytes($s)
        if ($rt.Length -eq 2 -and $rt[0] -eq $hi -and $rt[1] -eq $lo) {
            $pairs.Add([pscustomobject]@{ Gbk = ($hi -shl 8) -bor $lo; Uni = $uni })
        }
    }
}
$pairs = @($pairs | Sort-Object Gbk)
Write-Host "Mapping entries: $($pairs.Count)"

foreach ($p in $pairs) {
    $entries.Add(('    {0x' + $p.Gbk.ToString('X4') + ', 0x' + $p.Uni.ToString('X4') + '},'))
}

$header = @"
//--------------------------------------------------------------
//File name:   gbk_table.c
//Description: GB2312 double-byte code -> Unicode mapping table,
//             used to repair filenames stored as fake-UTF-16
//             (GBK bytes widened to 16-bit) by legacy tools.
//             Sorted by GBK code; lookup via binary search.
//             Generated by scripts/gen_gbk_table.ps1.
//--------------------------------------------------------------
#include "launchelf.h"

typedef struct GbkToUniEntry
{
    u16 gbk;
    u16 uni;
} GbkToUniEntry;

const GbkToUniEntry gbk_to_uni[] = {
"@
$footer = @"
};

const int gbk_to_uni_count = sizeof(gbk_to_uni) / sizeof(gbk_to_uni[0]);

u16 gbk_lookup_uni(u16 gbk)
{
    int lo = 0, hi = gbk_to_uni_count - 1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        if (gbk_to_uni[mid].gbk == gbk)
            return gbk_to_uni[mid].uni;
        if (gbk_to_uni[mid].gbk < gbk)
            lo = mid + 1;
        else
            hi = mid - 1;
    }
    return 0;
}
//--------------------------------------------------------------
//End of file:  gbk_table.c
//--------------------------------------------------------------
"@

[System.IO.File]::WriteAllText($outPath, ($header + "`r`n" + ($entries -join "`r`n") + $footer + "`r`n"), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Written: $outPath"
